clinico/appbase/urls.py
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    # Paciente
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    # Doctor
    path('Doctor/', DoctorView.as_view(), name='doctor'),
    path('crear_doctor/', CrearDoctorView.as_view(), name='crear_doctor'),
    path('editar_doctor/<int:pk>/', EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
    # Configuracion
    path('Configuracion/', InicioConfiguracion.as_view(), name='configuracion'),

    # Provincia
    path('Configuracion/Lista/Provincia/', ConfiguracionListView.as_view(), name='configuracion_listap'),
    path('Configuracion/Lista/Provincia/Nuevo', CrearProvinciaView.as_view(), name='crear_provincia'),
    path('Configuracion/Lista/Provincia/editar_provincia/<int:pk>/', EditarProvinciaView.as_view(),
         name='editar_provincia'),
    path('Configuracion/Lista/Provincia/eliminar_provincia/<int:pk>/',
         EliminarProvinciaView.as_view(), name='eliminar_provincia'),

    # Ciudad
    path('Configuracion/Lista/Ciudad/', ConfiguracionListCiudadView.as_view(), name='configuracion_listac'),
    path('Configuracion/Lista/Ciudad/Nuevo', CrearCiudadView.as_view(), name='crear_ciudad'),
    path('Configuracion/Lista/Ciudad/editar_ciudad/<int:pk>/', EditarCiudadView.as_view(),
         name='editar_ciudad'),
    path('Configuracion/Lista/Ciudad/eliminar_ciudad/<int:pk>/',
         EliminarCiudadView.as_view(), name='eliminar_ciudad'),

    # Profesion
    path('Configuracion/Lista/Profesion/', ConfiguracionListProfesiondView.as_view(), name='configuracion_listapro'),
    path('Configuracion/Lista/Profesion/Nuevo', CrearProfesionView.as_view(), name='crear_profesion'),
    path('Configuracion/Lista/Profesion/editar_profesion/<int:pk>/', EditarProfesionView.as_view(),
         name='editar_profesion'),
    path('Configuracion/Lista/Profesion/eliminar_profesion/<int:pk>/',
         EliminarProfesionView.as_view(), name='eliminar_profesion'),

    # Titulo
    path('Configuracion/Lista/Titulo/', ConfiguracionListTituloView.as_view(), name='configuracion_listati'),
    path('Configuracion/Lista/Titulo/Nuevo', CrearTituloView.as_view(), name='crear_titulo'),
    path('Configuracion/Lista/Titulo/editar_titulo/<int:pk>/', EditarTituloView.as_view(),
         name='editar_titulo'),
    path('Configuracion/Lista/Titulo/eliminar_titulo/<int:pk>/',
         EliminarTituloView.as_view(), name='eliminar_titulo'),
    # Sangre
    path('Configuracion/Lista/Sangre/', ConfiguracionListSangreView.as_view(), name='configuracion_listasa'),
    path('Configuracion/Lista/Sangre/Nuevo', CrearSangreView.as_view(), name='crear_sangre'),
    path('Configuracion/Lista/Sangre/editar_titulo/<int:pk>/', EditarSangreView.as_view(),
         name='editar_sangre'),
    path('Configuracion/Lista/Sangre/eliminar_titulo/<int:pk>/',
         EliminarSangreView.as_view(), name='eliminar_sangre'),

    # Horario
    path('Configuracion/Lista/Horario/', ConfiguracionListHorarioView.as_view(), name='configuracion_listaho'),
    path('Configuracion/Lista/Horario/Nuevo', CrearHorarioView.as_view(), name='crear_horario'),
    path('Configuracion/Lista/Horario/editar_horario/<int:pk>/', EditarHorarioView.as_view(),
         name='editar_horario'),
    path('Configuracion/Lista/Horario/eliminar_horario/<int:pk>/',
         EliminarHorarioView.as_view(), name='eliminar_horario'),
    # Grupo Antecedente
    path('Configuracion/Lista/Grupo_Antecedente/', ConfiguracionListGAntecedenteView.as_view(),
         name='configuracion_listaga'),
    path('Configuracion/Lista/Grupo_Antecedente/Nuevo', CrearGAntecedenteView.as_view(), name='crear_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/editar_gantecedente/<int:pk>/', EditarGAntecedenteView.as_view(),
         name='editar_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/eliminar_gantecedente/<int:pk>/',
         EliminarGAntecedenteView.as_view(), name='eliminar_gantecedente'),

    #  Antecedente
    path('Configuracion/Lista/Antecedente/', ConfiguracionListAntecedenteView.as_view(),
         name='configuracion_listaa'),
    path('Configuracion/Lista/Antecedente/Nuevo', CrearAntecedenteView.as_view(), name='crear_antecedente'),
    path('Configuracion/Lista/Antecedente/editar_antecedente/<int:pk>/', EditarAntecedenteView.as_view(),
         name='editar_antecedente'),
    path('Configuracion/Lista/Antecedente/eliminar_antecedente/<int:pk>/',
         EliminarAntecedenteView.as_view(), name='eliminar_antecedente'),

    #  Medicamento
    path('Configuracion/Lista/Medicamento/', ConfiguracionListMedicamentoView.as_view(),
         name='configuracion_listame'),
    path('Configuracion/Lista/Medicamento/Nuevo', CrearMedicamentoView.as_view(), name='crear_medicamento'),
    path('Configuracion/Lista/Medicamento/editar_medicamento/<int:pk>/', EditarMedicamentoView.as_view(),
         name='editar_medicamento'),
    path('Configuracion/Lista/Medicamento/eliminar_medicamento/<int:pk>/',
         EliminarMedicamentoView.as_view(), name='eliminar_medicamento'),

    #  Frecuencia
    path('Configuracion/Lista/Frecuencia/', ConfiguracionListFrecuenciaView.as_view(),
         name='configuracion_listafe'),
    path('Configuracion/Lista/Frecuencia/Nuevo', CrearFrecuenciaView.as_view(), name='crear_frecuencia'),
    path('Configuracion/Lista/Frecuencia/editar_frecuencia/<int:pk>/', EditarFrecuenciaView.as_view(),
         name='editar_frecuencia'),
    path('Configuracion/Lista/Frecuencia/eliminar_frecuencia/<int:pk>/',
         EliminarFrecuenciaView.as_view(), name='eliminar_frecuencia'),
    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Duracion
    path('Configuracion/Lista/Duracion/', ConfiguracionListDuracionView.as_view(),
         name='configuracion_listadu'),
    path('Configuracion/Lista/Duracion/Nuevo', CrearDuracionView.as_view(), name='crear_duracion'),
    path('Configuracion/Lista/Duracion/editar_duracion/<int:pk>/', EditarDuracionView.as_view(),
         name='editar_duracion'),
    path('Configuracion/Lista/Duracion/eliminar_duracion/<int:pk>/',
         EliminarDuracionView.as_view(), name='eliminar_duracion'),
    #  Sintoma
    path('Configuracion/Lista/Sintoma/', ConfiguracionListSintomaView.as_view(),
         name='configuracion_listasin'),
    path('Configuracion/Lista/Sintoma/Nuevo', CrearSintomaView.as_view(), name='crear_sintoma'),
    path('Configuracion/Lista/Sintoma/editar_sintoma/<int:pk>/', EditarSintomaView.as_view(),
         name='editar_sintoma'),
    path('Configuracion/Lista/Sintoma/eliminar_duracion/<int:pk>/',
         EliminarSintomaView.as_view(), name='eliminar_sintoma'),
    #  Diagnostico
    path('Configuracion/Lista/Diagnostico/', ConfiguracionListDiagnosticoView.as_view(),
         name='configuracion_listadia'),
    path('Configuracion/Lista/Diagnostico/Nuevo', CrearDiagnosticoView.as_view(), name='crear_diagnostico'),
    path('Configuracion/Lista/Diagnostico/editar_diagnostico/<int:pk>/', EditarDiagnosticoView.as_view(),
         name='editar_diagnostico'),
    path('Configuracion/Lista/Diagnostico/eliminar_diagnostico/<int:pk>/',
         EliminarDiagnosticoView.as_view(), name='eliminar_diagnostico'),

    #  SignoVital
    path('Configuracion/Lista/SignoVital/', ConfiguracionListSignoVitalView.as_view(),
         name='configuracion_listasv'),
    path('Configuracion/Lista/SignoVital/Nuevo', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('Configuracion/Lista/SignoVital/editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(),
         name='editar_signovital'),
    path('Configuracion/Lista/SignoVital/eliminar_signovital/<int:pk>/',
         EliminarSignoVitalView.as_view(), name='eliminar_signovital'),

    #  Estudio de Gabinete
    path('Configuracion/Lista/EstudioGabinete/', ConfiguracionListEstudioGabineteView.as_view(),
         name='configuracion_listaseg'),
    path('Configuracion/Lista/EstudioGabinete/Nuevo', CrearEstudioGabineteView.as_view(), name='crear_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/editar_estudiogabinete/<int:pk>/', EditarEstudioGabineteView.as_view(),
         name='editar_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/eliminar_estudiogabinete/<int:pk>/',
         EliminarEstudioGabineteView.as_view(), name='eliminar_estudiogabinete'),

    # Agenda
    path('Agenda/', AgendaView.as_view(), name='agenda'),

    # Cita
    path('cita/', CitaView.as_view(), name='cita'),
    path('cita/editar_cita/<int:pk>/', EditarcitaView.as_view(),
         name='editar_cita'),
    path('cita/eliminar_cita/<int:pk>/', EliminarcitaView.as_view(),
         name='eliminar_cita'),




]

clinico/templates/base/configuracion/Configuracion.html
{% extends "Principal.html" %}
{% load static %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a>Configuracion/</a></li>

            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>
    <div class="row" id="example">

        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listap' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Provincias</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listac' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Ciudad</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listapro' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Profesion</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listati' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Titulo</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listasa' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Sangre</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listaho' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Horario</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listaga' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Grupo Antecedente</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listaa' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Antecedente</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">

            <center>
                <a href="{% url 'base:configuracion_listame' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Medicamento</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listafe' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Frecuencia</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listado' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Dosis</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listadu' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Duracion</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listasin' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Sintoma</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listadia' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Diagnostico</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listasv' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Signo Vital</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
        <div class="col-md-2">
            <center>
                <a href="{% url 'base:configuracion_listaseg' %}" style="color: black">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" style="width: 100px; height: 100px"
                             src="{% static "image/settingscog_87317.png" %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Estudio de Gabinete</h5>

                        </div>
                    </div>
                </a>
            </center>
        </div>
    </div>
    <!-- inicio formulario Modal para Eliminar -->

    <div class="modal fade" id="myModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_doctor' 0 %} ">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
        </div>
    </div>
    <!-- Final Formulario Modal-->

    </div>
{% endblock %}

clinico/templates/base/configuracion/ListAntecedente.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
{% endblock %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a href="/base/Configuracion/">Configuracion/</a></li>
                <li><a>Listado Antecedente/</a></li>
            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/base/Configuracion/" class="btn btn-danger"><span class="fa fa-caret-left"></span>
                    Regresar</a>
                <a href="/base/Configuracion/Lista/Antecedente/Nuevo" class="btn btn-success"><span
                        class="fa fa-plus"></span> Nuevo</a>
            </div>
        </div>
        <hr>
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">Grupo Antecedente</th>
                <th class="text-center">Antecedente</th>
                <th class="text-center">Estado</th>
                <th class="text-center">Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for paciente in antecedentes %}
                <td>{{ paciente.id }}</td>
                <td>{{ paciente.grupoAntecedente }}</td>
                <td>{{ paciente.descripcion }}</td>
                <td>{{ paciente.estado }}</td>

                <td class="text-center"><a class="btn btn-primary btn-sm"
                                           href="{% url 'base:editar_antecedente' paciente.id %}">Editar</a>

                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{ paciente.id }}"}'
                       class="btn btn-danger btn-sm" href="#">Eliminar</a>
                </td>
                </tr>
            {% empty %}
                <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                    <strong>Mensaje del Sistema!</strong> No existen Pacientes registrados
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">Grupo Antecedente</th>
                <th class="text-center">Antecedente</th>
                <th class="text-center">Estado</th>
                <th class="text-center">Acciones</th>
            </tr>
            </tfoot>
        </table>
    </div>
    <!-- inicio formulario Modal para Eliminar -->

    <div class="modal fade" id="myModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form name="frmEliminar" id="frmEliminar" method="POST"
                      action="{% url 'base:eliminar_gantecedente' 0 %} ">
                    {% csrf_token %}
                    <div class="modal-header bg-primary text-light">
                        <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="action" value="elim">
                        <div class="h3 text-center">
                            <label class="text-primary font-weight-bold">Esta Seguro De Eliminar el Antecedente:</label>
                            <span class="text-light font-weight-bold badge badge-danger badge-pill"
                                  id="descripcion"></span><br>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Eliminar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Final Formulario Modal-->
{% endblock %}
{% block js %}
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
        $(function () {

            $('#example').on('click', 'a[rel="action"]', function () {
                let data = $(this).data('json'),
                    action = data.accion,
                    id = data.id;
                let desc = $(this).parents('tr').children('td').eq(2).html();
                $('#descripcion').html(desc);
                $('#frmEliminar #id').val(id);
                $('#myModal').modal('show');
                return;

            });

        })

        function convertir() {
            let titulo = document.getElementById("titulo").innerText
            document.getElementById("titulo").innerText = titulo.toUpperCase()
            alert(titulo)
        }
    </script>
{% endblock %}

clinico/templates/base/configuracion/ManCiudad.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
{% endblock %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a href="/base/Configuracion/">Configuracion/</a></li>
                <li><a href="/base/Configuracion/Lista/Ciudad/">Listado de Ciudad/</a></li>
                <li><a>Nuevo/</a></li>
            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/base/Configuracion/Lista/Ciudad/" class="btn btn-danger"><span
                        class="fa fa-caret-left"></span>
                    Regresar</a>
            </div>
        </div>
        <hr>
        <form method="POST" enctype="multipart/form-data" style="position: relative;z-index: 1">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="/base/Configuracion/Lista/Ciudad/" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>

{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% endblock %}

clinico/templates/base/configuracion/ManDosis.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
{% endblock %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a href="/base/Configuracion/">Configuracion/</a></li>
                <li><a href="/base/Configuracion/Lista/Dosis/">Listado Dosis/</a></li>
                <li><a>Nuevo/</a></li>
            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/base/Configuracion/Lista/Dosis/" class="btn btn-danger"><span
                        class="fa fa-caret-left"></span>
                    Regresar</a>
            </div>
        </div>
        <hr>
        <form method="POST" enctype="multipart/form-data" style="position: relative;z-index: 1">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="/base/Configuracion/Lista/Dosis/" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>

{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% endblock %}