clinico/appbase/urls.py
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    # Paciente
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    # Doctor
    path('Doctor/', DoctorView.as_view(), name='doctor'),
    path('crear_doctor/', CrearDoctorView.as_view(), name='crear_doctor'),
    path('editar_doctor/<int:pk>/', EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
    # Configuracion
    path('Configuracion/', InicioConfiguracion.as_view(), name='configuracion'),

    # Provincia
    path('Configuracion/Lista/Provincia/', ConfiguracionListView.as_view(), name='configuracion_listap'),
    path('Configuracion/Lista/Provincia/Nuevo', CrearProvinciaView.as_view(), name='crear_provincia'),
    path('Configuracion/Lista/Provincia/editar_provincia/<int:pk>/', EditarProvinciaView.as_view(),
         name='editar_provincia'),
    path('Configuracion/Lista/Provincia/eliminar_provincia/<int:pk>/',
         EliminarProvinciaView.as_view(), name='eliminar_provincia'),

    # Ciudad
    path('Configuracion/Lista/Ciudad/', ConfiguracionListCiudadView.as_view(), name='configuracion_listac'),
    path('Configuracion/Lista/Ciudad/Nuevo', CrearCiudadView.as_view(), name='crear_ciudad'),
    path('Configuracion/Lista/Ciudad/editar_ciudad/<int:pk>/', EditarCiudadView.as_view(),
         name='editar_ciudad'),
    path('Configuracion/Lista/Ciudad/eliminar_ciudad/<int:pk>/',
         EliminarCiudadView.as_view(), name='eliminar_ciudad'),

    # Profesion
    path('Configuracion/Lista/Profesion/', ConfiguracionListProfesiondView.as_view(), name='configuracion_listapro'),
    path('Configuracion/Lista/Profesion/Nuevo', CrearProfesionView.as_view(), name='crear_profesion'),
    path('Configuracion/Lista/Profesion/editar_profesion/<int:pk>/', EditarProfesionView.as_view(),
         name='editar_profesion'),
    path('Configuracion/Lista/Profesion/eliminar_profesion/<int:pk>/',
         EliminarProfesionView.as_view(), name='eliminar_profesion'),

    # Titulo
    path('Configuracion/Lista/Titulo/', ConfiguracionListTituloView.as_view(), name='configuracion_listati'),
    path('Configuracion/Lista/Titulo/Nuevo', CrearTituloView.as_view(), name='crear_titulo'),
    path('Configuracion/Lista/Titulo/editar_titulo/<int:pk>/', EditarTituloView.as_view(),
         name='editar_titulo'),
    path('Configuracion/Lista/Titulo/eliminar_titulo/<int:pk>/',
         EliminarTituloView.as_view(), name='eliminar_titulo'),
    # Sangre
    path('Configuracion/Lista/Sangre/', ConfiguracionListSangreView.as_view(), name='configuracion_listasa'),
    path('Configuracion/Lista/Sangre/Nuevo', CrearSangreView.as_view(), name='crear_sangre'),
    path('Configuracion/Lista/Sangre/editar_titulo/<int:pk>/', EditarSangreView.as_view(),
         name='editar_sangre'),
    path('Configuracion/Lista/Sangre/eliminar_titulo/<int:pk>/',
         EliminarSangreView.as_view(), name='eliminar_sangre'),

    # Horario
    path('Configuracion/Lista/Horario/', ConfiguracionListHorarioView.as_view(), name='configuracion_listaho'),
    path('Configuracion/Lista/Horario/Nuevo', CrearHorarioView.as_view(), name='crear_horario'),
    path('Configuracion/Lista/Horario/editar_horario/<int:pk>/', EditarHorarioView.as_view(),
         name='editar_horario'),
    path('Configuracion/Lista/Horario/eliminar_horario/<int:pk>/',
         EliminarHorarioView.as_view(), name='eliminar_horario'),
    # Grupo Antecedente
    path('Configuracion/Lista/Grupo_Antecedente/', ConfiguracionListGAntecedenteView.as_view(),
         name='configuracion_listaga'),
    path('Configuracion/Lista/Grupo_Antecedente/Nuevo', CrearGAntecedenteView.as_view(), name='crear_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/editar_gantecedente/<int:pk>/', EditarGAntecedenteView.as_view(),
         name='editar_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/eliminar_gantecedente/<int:pk>/',
         EliminarGAntecedenteView.as_view(), name='eliminar_gantecedente'),

    #  Antecedente
    path('Configuracion/Lista/Antecedente/', ConfiguracionListAntecedenteView.as_view(),
         name='configuracion_listaa'),
    path('Configuracion/Lista/Antecedente/Nuevo', CrearAntecedenteView.as_view(), name='crear_antecedente'),
    path('Configuracion/Lista/Antecedente/editar_antecedente/<int:pk>/', EditarAntecedenteView.as_view(),
         name='editar_antecedente'),
    path('Configuracion/Lista/Antecedente/eliminar_antecedente/<int:pk>/',
         EliminarAntecedenteView.as_view(), name='eliminar_antecedente'),

    #  Medicamento
    path('Configuracion/Lista/Medicamento/', ConfiguracionListMedicamentoView.as_view(),
         name='configuracion_listame'),
    path('Configuracion/Lista/Medicamento/Nuevo', CrearMedicamentoView.as_view(), name='crear_medicamento'),
    path('Configuracion/Lista/Medicamento/editar_medicamento/<int:pk>/', EditarMedicamentoView.as_view(),
         name='editar_medicamento'),
    path('Configuracion/Lista/Medicamento/eliminar_medicamento/<int:pk>/',
         EliminarMedicamentoView.as_view(), name='eliminar_medicamento'),

    #  Frecuencia
    path('Configuracion/Lista/Frecuencia/', ConfiguracionListFrecuenciaView.as_view(),
         name='configuracion_listafe'),
    path('Configuracion/Lista/Frecuencia/Nuevo', CrearFrecuenciaView.as_view(), name='crear_frecuencia'),
    path('Configuracion/Lista/Frecuencia/editar_frecuencia/<int:pk>/', EditarFrecuenciaView.as_view(),
         name='editar_frecuencia'),
    path('Configuracion/Lista/Frecuencia/eliminar_frecuencia/<int:pk>/',
         EliminarFrecuenciaView.as_view(), name='eliminar_frecuencia'),
    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Duracion
    path('Configuracion/Lista/Duracion/', ConfiguracionListDuracionView.as_view(),
         name='configuracion_listadu'),
    path('Configuracion/Lista/Duracion/Nuevo', CrearDuracionView.as_view(), name='crear_duracion'),
    path('Configuracion/Lista/Duracion/editar_duracion/<int:pk>/', EditarDuracionView.as_view(),
         name='editar_duracion'),
    path('Configuracion/Lista/Duracion/eliminar_duracion/<int:pk>/',
         EliminarDuracionView.as_view(), name='eliminar_duracion'),
    #  Sintoma
    path('Configuracion/Lista/Sintoma/', ConfiguracionListSintomaView.as_view(),
         name='configuracion_listasin'),
    path('Configuracion/Lista/Sintoma/Nuevo', CrearSintomaView.as_view(), name='crear_sintoma'),
    path('Configuracion/Lista/Sintoma/editar_sintoma/<int:pk>/', EditarSintomaView.as_view(),
         name='editar_sintoma'),
    path('Configuracion/Lista/Sintoma/eliminar_duracion/<int:pk>/',
         EliminarSintomaView.as_view(), name='eliminar_sintoma'),
    #  Diagnostico
    path('Configuracion/Lista/Diagnostico/', ConfiguracionListDiagnosticoView.as_view(),
         name='configuracion_listadia'),
    path('Configuracion/Lista/Diagnostico/Nuevo', CrearDiagnosticoView.as_view(), name='crear_diagnostico'),
    path('Configuracion/Lista/Diagnostico/editar_diagnostico/<int:pk>/', EditarDiagnosticoView.as_view(),
         name='editar_diagnostico'),
    path('Configuracion/Lista/Diagnostico/eliminar_diagnostico/<int:pk>/',
         EliminarDiagnosticoView.as_view(), name='eliminar_diagnostico'),

    #  SignoVital
    path('Configuracion/Lista/SignoVital/', ConfiguracionListSignoVitalView.as_view(),
         name='configuracion_listasv'),
    path('Configuracion/Lista/SignoVital/Nuevo', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('Configuracion/Lista/SignoVital/editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(),
         name='editar_signovital'),
    path('Configuracion/Lista/SignoVital/eliminar_signovital/<int:pk>/',
         EliminarSignoVitalView.as_view(), name='eliminar_signovital'),

    #  Estudio de Gabinete
    path('Configuracion/Lista/EstudioGabinete/', ConfiguracionListEstudioGabineteView.as_view(),
         name='configuracion_listaseg'),
    path('Configuracion/Lista/EstudioGabinete/Nuevo', CrearEstudioGabineteView.as_view(), name='crear_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/editar_estudiogabinete/<int:pk>/', EditarEstudioGabineteView.as_view(),
         name='editar_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/eliminar_estudiogabinete/<int:pk>/',
         EliminarEstudioGabineteView.as_view(), name='eliminar_estudiogabinete'),

    # Agenda
    path('Agenda/', AgendaView.as_view(), name='agenda'),

    # Cita
    path('cita/', CitaView.as_view(), name='cita'),
    path('cita/editar_cita/<int:pk>/', EditarcitaView.as_view(),
         name='editar_cita'),
    path('cita/eliminar_cita/<int:pk>/', EliminarcitaView.as_view(),
         name='eliminar_cita'),




]

clinico/appconsulta/urls.py
from django.urls import path
from .views import *

app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),

# Consulta
    path('consulta/', ConsultaView.as_view(), name='consulta'),

]

clinico/appconsulta/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime, date
from appbase.models import (Paciente, Sintoma, Diagnostico,
                            EstudioGabinete, Medicamento, Dosis, Frecuencia,
                            Duracion, SignoVital, Paciente, Antecedente, GrupoAntecedente)


class Receta(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Atencion', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    motivo = models.CharField('Motivo de Consulta', max_length=50)
    sintoma = models.ForeignKey(Sintoma, on_delete=models.PROTECT)
    exploracion = models.TextField('Exploracion Fisica')
    diagnostico = models.ManyToManyField(Diagnostico, null=True)
    gabinete = models.ManyToManyField(
        EstudioGabinete, null=True)
    instrucciones = models.TextField('Instrucciones Medicas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Receta'
        verbose_name_plural = 'Recetas'

    def __str__(self):
        return '{}'.format(self.fecha)


class DetalleReceta(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    medicamento = models.ForeignKey(Medicamento, on_delete=models.PROTECT)
    cantidad = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    dosis = models.ForeignKey(Dosis, on_delete=models.PROTECT)
    frecuencia = models.ForeignKey(Frecuencia, on_delete=models.PROTECT)
    duracion = models.ForeignKey(Duracion, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'DetalleReceta'
        verbose_name_plural = 'DetalleRecetas'

    def __str__(self):
        return '{}'.format(self.id)


class TomarSignoVital(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    signovital = models.ForeignKey(SignoVital, on_delete=models.PROTECT)
    valor = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tomar Signo Vital'
        verbose_name_plural = 'Tomar Signo Vitales'

    def __str__(self):
        return '{}'.format(self.id)


class Historia(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Historia', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    historiaNo = models.CharField('Numero de Historia', max_length=50)
    notasinterna = models.TextField('Notas Internas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Historia'
        verbose_name_plural = 'Historia Clinicas'

    def __str__(self):
        return '{}'.format(self.fecha)


class HistoriaDetalle(models.Model):
    historia = models.ForeignKey(Historia, on_delete=models.PROTECT)
    GrupoAntecedente = models.ForeignKey(
        GrupoAntecedente, on_delete=models.PROTECT, null=True, blank=True)
    antecedente = models.ForeignKey(Antecedente, on_delete=models.PROTECT)
    descripcion = models.CharField('Antecedente', max_length=300)

    class Meta:
        verbose_name = 'Detalle de la Historia Clinica'
        verbose_name_plural = 'Detalle de las Historias Clinicas'

    def __str__(self):
        return '{}'.format(self.descripcion)

clinico/templates/base/paciente/ListPaciente.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
{% endblock %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a>Listado de Paciente/</a></li>

            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/" class="btn btn-danger"><span class="fa fa-caret-left"></span> Regresar</a>
                <a href="/base/crear_paciente/" class="btn btn-success"><span class="fa fa-plus"></span> Nuevo</a>
            </div>
        </div>
        <hr>
        <table id="tabla" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th class="text-center">Foto</th>
                <th class="text-center">Nombre</th>
                <th class="text-center">Genero</th>
                <th class="text-center">Correo</th>
                <th class="text-center">Telefono</th>
                <th class="text-center">Ciudad</th>
                <th class="text-center">Direccion</th>
                <th class="text-center">Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for paciente in pacientes %}
                <tr>
                    {% if paciente.foto %}
                        <td><img src="{{ paciente.foto.url }}" class="img-thumbnail rounded-circle" width="40px">
                        </td>
                    {% else %}
                        <td><img src="{% static 'imagenes/sinimagen.png' %}"
                                 class="img-thumbnail rounded-circle" width="40px">
                        </td>
                    {% endif %}

                    <td><span>{{ paciente.nombre }}</span></td>
                    {% if paciente.sexo == 'M' %}
                        <td class="text-center"><span
                                class="label label-success">{{ paciente.sexo }}</span>
                        </td>
                    {% else %}
                        <td class="text-center"><span
                                class="label label-danger">{{ paciente.sexo }}</span>
                        </td>
                    {% endif %}

                    <td>{{ paciente.email }}</td>
                    <td>{{ paciente.telefono }}</td>
                    <td>{{ paciente.ciudad }}</td>
                    <td>{{ paciente.direccion }}</td>

                    <td class="text-center"><a class="btn btn-primary btn-sm"
                                               href="{% url 'base:editar_paciente' paciente.id %}">Editar</a>
                        <a class="btn btn-primary btn-sm"
                           href="{% url 'atencion:historia' %}?id_paciente={{ paciente.id }}">Historia</a>
                        <a rel="action" data-json='{"accion":"elim" ,"id":"{{ paciente.id }}"}'
                           class="btn btn-danger btn-sm" href="#">Eliminar</a>
                    </td>
                </tr>
            {% empty %}
                <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                    <strong>Mensaje del Sistema!</strong> No existen Pacientes registrados
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
            <tfoot>
            <tr>
                <th class="text-center">Foto</th>
                <th class="text-center">Nombre</th>
                <th class="text-center">Genero</th>
                <th class="text-center">Correo</th>
                <th class="text-center">Telefono</th>
                <th class="text-center">Ciudad</th>
                <th class="text-center">Direccion</th>
                <th class="text-center">Acciones</th>
            </tr>
            </tfoot>
        </table>
    </div>
    <!-- inicio formulario Modal para Eliminar -->

    <div class="modal fade" id="myModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_paciente' 0 %} ">
                    {% csrf_token %}
                    <div class="modal-header bg-primary text-light">
                        <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="action" value="elim">
                        <div class="h3 text-center">
                            <label class="text-primary font-weight-bold">Esta Seguro De Eliminar El Paciente:</label>
                            <span class="text-light font-weight-bold badge badge-danger badge-pill"
                                  id="descripcion"></span><br>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Eliminar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Final Formulario Modal-->
{% endblock %}
{% block js %}
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#tabla').DataTable();

        });
        $(function () {

            $('#tabla').on('click', 'a[rel="action"]', function () {
                let data = $(this).data('json'),
                    action = data.accion,
                    id = data.id;
                let desc = $(this).parents('tr').children('td').eq(1).html();
                $('#descripcion').html(desc);
                $('#frmEliminar #id').val(id);
                $('#myModal').modal('show');
                return;

            });

        })

        function convertir() {
            let titulo = document.getElementById("titulo").innerText
            document.getElementById("titulo").innerText = titulo.toUpperCase()
            alert(titulo)
        }
    </script>
{% endblock %}

clinico/templates/base/paciente/paciente.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                    <h3 id="titulo" class="font-weight-bold" onclick="convertir()">{{titulo}}</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:crear_paciente' %}" class="btn btn-primary float-right">Nuevo Registro</a>
                </div>

            </div>
        </div>
        <div class="card-body table-responsive">

            <form class="row">

                <div class="col-md-8">
                    <input class="form-control mr-2 bg-info text-danger font-weight-bold " placeholder="Texto a Buscar"
                        name="nombre" value={{nombre}}>
                </div>
                <div class="col-md-4 ">
                    <button class="btn btn-primary" type="submit">Buscar</button>
                </div>
            </form>

            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Foto</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Genero</th>
                                <th class="text-center">Correo</th>
                                <th class="text-center">Telefono</th>
                                <th class="text-center">Ciudad</th>
                                <th class="text-center">Direccion</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for paciente in pacientes%}
                            <tr>
                                {% if paciente.foto %}
                                <td><img src="{{paciente.foto.url}}" class="img-thumbnail rounded-circle" width="40px">
                                </td>
                                {% else %}
                                <td><img src="{% static 'imagenes/sinimagen.png' %}"
                                        class="img-thumbnail rounded-circle" width="40px">
                                </td>
                                {% endif %}

                                <td><span>{{paciente.nombre}}</span> </td>
                                {% if paciente.sexo == 'M' %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-success">{{paciente.sexo}}</span>
                                </td>
                                {% else %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-danger">{{paciente.sexo}}</span>
                                </td>
                                {% endif %}

                                <td>{{paciente.email}}</td>
                                <td>{{paciente.telefono}}</td>
                                <td>{{paciente.ciudad}}</td>
                                <td>{{paciente.direccion}}</td>

                                <td class="text-center"><a class="btn btn-primary btn-sm"
                                        href="{% url 'base:editar_paciente' paciente.id %}">Editar</a>
                                <td class="text-center"><a class="btn btn-primary btn-sm"
                                        href="{% url 'atencion:historia' %}?id_paciente={{paciente.id}}">Historia</a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{paciente.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Pacientes registrados
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Menú de paginación -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link"
                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                    {% if page_obj.number == i %}
                    <li class="page-item active" style="pointer-events:none">
                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ forloop.counter }}{{ url }}" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- Fin del pagineo -->
        </div>
    </div>



</div>
{% endblock %}

{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_paciente' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar El Paciente:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->
{% endblock %}

{% block jscript %}
<script>
    $(function () {

        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(1).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;

        });

    })

    function convertir() {
        let titulo = document.getElementById("titulo").innerText
        document.getElementById("titulo").innerText = titulo.toUpperCase()
        alert(titulo)
    }
</script>
{% endblock %}