clinico/appbase/urls.py
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    # Paciente
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    # Doctor
    path('Doctor/', DoctorView.as_view(), name='doctor'),
    path('crear_doctor/', CrearDoctorView.as_view(), name='crear_doctor'),
    path('editar_doctor/<int:pk>/', EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
    # Configuracion
    path('Configuracion/', InicioConfiguracion.as_view(), name='configuracion'),

    # Provincia
    path('Configuracion/Lista/Provincia/', ConfiguracionListView.as_view(), name='configuracion_listap'),
    path('Configuracion/Lista/Provincia/Nuevo', CrearProvinciaView.as_view(), name='crear_provincia'),
    path('Configuracion/Lista/Provincia/editar_provincia/<int:pk>/', EditarProvinciaView.as_view(),
         name='editar_provincia'),
    path('Configuracion/Lista/Provincia/eliminar_provincia/<int:pk>/',
         EliminarProvinciaView.as_view(), name='eliminar_provincia'),

    # Ciudad
    path('Configuracion/Lista/Ciudad/', ConfiguracionListCiudadView.as_view(), name='configuracion_listac'),
    path('Configuracion/Lista/Ciudad/Nuevo', CrearCiudadView.as_view(), name='crear_ciudad'),
    path('Configuracion/Lista/Ciudad/editar_ciudad/<int:pk>/', EditarCiudadView.as_view(),
         name='editar_ciudad'),
    path('Configuracion/Lista/Ciudad/eliminar_ciudad/<int:pk>/',
         EliminarCiudadView.as_view(), name='eliminar_ciudad'),

    # Profesion
    path('Configuracion/Lista/Profesion/', ConfiguracionListProfesiondView.as_view(), name='configuracion_listapro'),
    path('Configuracion/Lista/Profesion/Nuevo', CrearProfesionView.as_view(), name='crear_profesion'),
    path('Configuracion/Lista/Profesion/editar_profesion/<int:pk>/', EditarProfesionView.as_view(),
         name='editar_profesion'),
    path('Configuracion/Lista/Profesion/eliminar_profesion/<int:pk>/',
         EliminarProfesionView.as_view(), name='eliminar_profesion'),

    # Titulo
    path('Configuracion/Lista/Titulo/', ConfiguracionListTituloView.as_view(), name='configuracion_listati'),
    path('Configuracion/Lista/Titulo/Nuevo', CrearTituloView.as_view(), name='crear_titulo'),
    path('Configuracion/Lista/Titulo/editar_titulo/<int:pk>/', EditarTituloView.as_view(),
         name='editar_titulo'),
    path('Configuracion/Lista/Titulo/eliminar_titulo/<int:pk>/',
         EliminarTituloView.as_view(), name='eliminar_titulo'),
    # Sangre
    path('Configuracion/Lista/Sangre/', ConfiguracionListSangreView.as_view(), name='configuracion_listasa'),
    path('Configuracion/Lista/Sangre/Nuevo', CrearSangreView.as_view(), name='crear_sangre'),
    path('Configuracion/Lista/Sangre/editar_titulo/<int:pk>/', EditarSangreView.as_view(),
         name='editar_sangre'),
    path('Configuracion/Lista/Sangre/eliminar_titulo/<int:pk>/',
         EliminarSangreView.as_view(), name='eliminar_sangre'),

    # Horario
    path('Configuracion/Lista/Horario/', ConfiguracionListHorarioView.as_view(), name='configuracion_listaho'),
    path('Configuracion/Lista/Horario/Nuevo', CrearHorarioView.as_view(), name='crear_horario'),
    path('Configuracion/Lista/Horario/editar_horario/<int:pk>/', EditarHorarioView.as_view(),
         name='editar_horario'),
    path('Configuracion/Lista/Horario/eliminar_horario/<int:pk>/',
         EliminarHorarioView.as_view(), name='eliminar_horario'),
    # Grupo Antecedente
    path('Configuracion/Lista/Grupo_Antecedente/', ConfiguracionListGAntecedenteView.as_view(),
         name='configuracion_listaga'),
    path('Configuracion/Lista/Grupo_Antecedente/Nuevo', CrearGAntecedenteView.as_view(), name='crear_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/editar_gantecedente/<int:pk>/', EditarGAntecedenteView.as_view(),
         name='editar_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/eliminar_gantecedente/<int:pk>/',
         EliminarGAntecedenteView.as_view(), name='eliminar_gantecedente'),

    #  Antecedente
    path('Configuracion/Lista/Antecedente/', ConfiguracionListAntecedenteView.as_view(),
         name='configuracion_listaa'),
    path('Configuracion/Lista/Antecedente/Nuevo', CrearAntecedenteView.as_view(), name='crear_antecedente'),
    path('Configuracion/Lista/Antecedente/editar_antecedente/<int:pk>/', EditarAntecedenteView.as_view(),
         name='editar_antecedente'),
    path('Configuracion/Lista/Antecedente/eliminar_antecedente/<int:pk>/',
         EliminarAntecedenteView.as_view(), name='eliminar_antecedente'),

    #  Medicamento
    path('Configuracion/Lista/Medicamento/', ConfiguracionListMedicamentoView.as_view(),
         name='configuracion_listame'),
    path('Configuracion/Lista/Medicamento/Nuevo', CrearMedicamentoView.as_view(), name='crear_medicamento'),
    path('Configuracion/Lista/Medicamento/editar_medicamento/<int:pk>/', EditarMedicamentoView.as_view(),
         name='editar_medicamento'),
    path('Configuracion/Lista/Medicamento/eliminar_medicamento/<int:pk>/',
         EliminarMedicamentoView.as_view(), name='eliminar_medicamento'),

    #  Frecuencia
    path('Configuracion/Lista/Frecuencia/', ConfiguracionListFrecuenciaView.as_view(),
         name='configuracion_listafe'),
    path('Configuracion/Lista/Frecuencia/Nuevo', CrearFrecuenciaView.as_view(), name='crear_frecuencia'),
    path('Configuracion/Lista/Frecuencia/editar_frecuencia/<int:pk>/', EditarFrecuenciaView.as_view(),
         name='editar_frecuencia'),
    path('Configuracion/Lista/Frecuencia/eliminar_frecuencia/<int:pk>/',
         EliminarFrecuenciaView.as_view(), name='eliminar_frecuencia'),
    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Duracion
    path('Configuracion/Lista/Duracion/', ConfiguracionListDuracionView.as_view(),
         name='configuracion_listadu'),
    path('Configuracion/Lista/Duracion/Nuevo', CrearDuracionView.as_view(), name='crear_duracion'),
    path('Configuracion/Lista/Duracion/editar_duracion/<int:pk>/', EditarDuracionView.as_view(),
         name='editar_duracion'),
    path('Configuracion/Lista/Duracion/eliminar_duracion/<int:pk>/',
         EliminarDuracionView.as_view(), name='eliminar_duracion'),
    #  Sintoma
    path('Configuracion/Lista/Sintoma/', ConfiguracionListSintomaView.as_view(),
         name='configuracion_listasin'),
    path('Configuracion/Lista/Sintoma/Nuevo', CrearSintomaView.as_view(), name='crear_sintoma'),
    path('Configuracion/Lista/Sintoma/editar_sintoma/<int:pk>/', EditarSintomaView.as_view(),
         name='editar_sintoma'),
    path('Configuracion/Lista/Sintoma/eliminar_duracion/<int:pk>/',
         EliminarSintomaView.as_view(), name='eliminar_sintoma'),
    #  Diagnostico
    path('Configuracion/Lista/Diagnostico/', ConfiguracionListDiagnosticoView.as_view(),
         name='configuracion_listadia'),
    path('Configuracion/Lista/Diagnostico/Nuevo', CrearDiagnosticoView.as_view(), name='crear_diagnostico'),
    path('Configuracion/Lista/Diagnostico/editar_diagnostico/<int:pk>/', EditarDiagnosticoView.as_view(),
         name='editar_diagnostico'),
    path('Configuracion/Lista/Diagnostico/eliminar_diagnostico/<int:pk>/',
         EliminarDiagnosticoView.as_view(), name='eliminar_diagnostico'),

    #  SignoVital
    path('Configuracion/Lista/SignoVital/', ConfiguracionListSignoVitalView.as_view(),
         name='configuracion_listasv'),
    path('Configuracion/Lista/SignoVital/Nuevo', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('Configuracion/Lista/SignoVital/editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(),
         name='editar_signovital'),
    path('Configuracion/Lista/SignoVital/eliminar_signovital/<int:pk>/',
         EliminarSignoVitalView.as_view(), name='eliminar_signovital'),

    #  Estudio de Gabinete
    path('Configuracion/Lista/EstudioGabinete/', ConfiguracionListEstudioGabineteView.as_view(),
         name='configuracion_listaseg'),
    path('Configuracion/Lista/EstudioGabinete/Nuevo', CrearEstudioGabineteView.as_view(), name='crear_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/editar_estudiogabinete/<int:pk>/', EditarEstudioGabineteView.as_view(),
         name='editar_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/eliminar_estudiogabinete/<int:pk>/',
         EliminarEstudioGabineteView.as_view(), name='eliminar_estudiogabinete'),

    # Agenda
    path('Agenda/', AgendaView.as_view(), name='agenda'),

    # Cita
    path('cita/', CitaView.as_view(), name='cita'),
    path('cita/editar_cita/<int:pk>/', EditarcitaView.as_view(),
         name='editar_cita'),
    path('cita/eliminar_cita/<int:pk>/', EliminarcitaView.as_view(),
         name='eliminar_cita'),




]

clinico/appconsulta/urls.py
from django.urls import path
from .views import *

app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),

# Consulta
    path('consulta/', ConsultaView.as_view(), name='consulta'),

]

clinico/appconsulta/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime, date
from appbase.models import (Paciente, Sintoma, Diagnostico,
                            EstudioGabinete, Medicamento, Dosis, Frecuencia,
                            Duracion, SignoVital, Paciente, Antecedente, GrupoAntecedente)


class Receta(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Atencion', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    motivo = models.CharField('Motivo de Consulta', max_length=50)
    sintoma = models.ForeignKey(Sintoma, on_delete=models.PROTECT)
    exploracion = models.TextField('Exploracion Fisica')
    diagnostico = models.ManyToManyField(Diagnostico, null=True)
    gabinete = models.ManyToManyField(
        EstudioGabinete, null=True)
    instrucciones = models.TextField('Instrucciones Medicas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Receta'
        verbose_name_plural = 'Recetas'

    def __str__(self):
        return '{}'.format(self.fecha)


class DetalleReceta(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    medicamento = models.ForeignKey(Medicamento, on_delete=models.PROTECT)
    cantidad = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    dosis = models.ForeignKey(Dosis, on_delete=models.PROTECT)
    frecuencia = models.ForeignKey(Frecuencia, on_delete=models.PROTECT)
    duracion = models.ForeignKey(Duracion, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'DetalleReceta'
        verbose_name_plural = 'DetalleRecetas'

    def __str__(self):
        return '{}'.format(self.id)


class TomarSignoVital(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    signovital = models.ForeignKey(SignoVital, on_delete=models.PROTECT)
    valor = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tomar Signo Vital'
        verbose_name_plural = 'Tomar Signo Vitales'

    def __str__(self):
        return '{}'.format(self.id)


class Historia(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Historia', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    historiaNo = models.CharField('Numero de Historia', max_length=50)
    notasinterna = models.TextField('Notas Internas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Historia'
        verbose_name_plural = 'Historia Clinicas'

    def __str__(self):
        return '{}'.format(self.fecha)


class HistoriaDetalle(models.Model):
    historia = models.ForeignKey(Historia, on_delete=models.PROTECT)
    GrupoAntecedente = models.ForeignKey(
        GrupoAntecedente, on_delete=models.PROTECT, null=True, blank=True)
    antecedente = models.ForeignKey(Antecedente, on_delete=models.PROTECT)
    descripcion = models.CharField('Antecedente', max_length=300)

    class Meta:
        verbose_name = 'Detalle de la Historia Clinica'
        verbose_name_plural = 'Detalle de las Historias Clinicas'

    def __str__(self):
        return '{}'.format(self.descripcion)

clinico/templates/atencion/historia/historia2.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% load static %}
{% endblock %}

{% block main %}

<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card ">
                <div class="row bg-success text-light p-0">
                    <div class="col-md-8 mt-3">
                        <h3 class=" ml-2 font-italic font-weight-bold">
                            {{title}}
                        </h3>
                    </div>
                    <div class="col-md-4 ">
                        <div class="float-right m-3">
                            <a href="{% url 'base:paciente' %}" class="btn btn-warning">
                                Cancelar
                            </a>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-5">
                    <div class="card mb-3 table-responsive">
                        <div class=" row no-gutters">
                            <div class="col-md-4">
                                {% if historia.paciente.foto %}
                                <img src="{{historia.paciente.foto.url}}" class="img-thumbnail rounded-circle"
                                    width="100%">

                                {% else %}
                                <img src="{% static 'imagenes/sinimagen.png' %}" class="img-thumbnail rounded-circle"
                                    width="100%">
                                {% endif %}

                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">Datos del Paciente</h5>
                                    <p class="card-text"> {{historia.paciente.nombre}} {{historia.paciente.apellido}}
                                    </p>
                                    <p class="card-text"> Email:{{historia.paciente.email}}
                                    </p>
                                    <p class="card-text"> Telefono:{{historia.paciente.telefono}}
                                    </p>
                                    <p class="card-text"> Direccion:{{historia.paciente.direccion}}
                                    </p>

                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">

                                <textarea class="form-control" id="id_notas_internas" placeholder="Notas Internas"
                                    rows="3">{{historia.notasinterna}}</textarea>
                            </div>
                        </div>
                        <div class="row">
                            <table class="table table-hover table-striped  m-1 ">
                                <thead class="bg-success text-light">
                                    <tr class="h5">
                                        <th>Signo Vital</th>
                                        <th>Valor Tomado</th>
                                    </tr>
                                </thead>
                                <tbody class="delegacion-container" id="contenedor">
                                    {% for signo in signo_vitales%}
                                    <tr class="text-justify">
                                        <td>{{signo.signovital.descripcion}} </td>
                                        <td>{{signo.valor}} {{signo.signovital.medida}}</td>

                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

                <div class="col-7">
                    <div class="card table-responsive">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST">
                                    <div class="form-group row">
                                        <div class="col-6">
                                            <select class="form-control" id="id_grupo_antecedente">
                                                <option selected value="0">Grupo Antecedente</option>
                                                {% for grupo in lt_grupo_antecedentes %}
                                                <option value="{{grupo.id}}">{{grupo}}</option>
                                                {% endfor %}

                                            </select>

                                        </div>
                                        <div class="col-6">
                                            <select class="form-control" id="id_antecedente">


                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <input type="text" class="form-control" id="id_descripcion_antecedente"
                                                placeholder="Escriba el antecedente">
                                        </div>
                                    </div>
                                    <button class="btn btn-primary btn-block" id="id_registrar_antecedente"
                                        type="button">Registrar
                                        Antecedente
                                    </button>

                                </form>
                            </div>
                        </div>
                        <div class="row">
                            <table class="table table-hover table-striped  m-1 ">
                                <thead class="bg-success text-light">
                                    <tr class="h5">
                                        <th>Antecedente</th>
                                        <th>Descripcion</th>
                                        <th class="text-center">Acciones</th>

                                    </tr>
                                </thead>
                                <tbody class="delegacion-container" id="id_contenedor">

                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
                <button class="btn btn-primary btn-block" id="id_actualizar" type="button">Actualizar Historia</button>

            </div>

        </div>
    </div>

</div>

{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
{% endblock %}

{% block jscript %}
<script>
    const c = console.log

    let lt_historia_detalle = [],
        id_seleccionado = 0,
        por_editar = false,
        lt_grupo_antecedente = [],
        id_momentaneo = 0,
        id_paciente = "{{historia.paciente_id}}",
        token = "{{ csrf_token }}"

    const cargar_combo = async (id_grupo_antecedente) => {

        $("#id_antecedente").empty()

        const response = await fetch(`{% url "atencion:historia" %}?action=data_antecedente&id_grupo_antecedente=${id_grupo_antecedente}`,
            {
                headers: {
                    'Content-Type': 'application/json'

                }
            }
        )

        const resultado = await response.json()
        if (resultado.result == "ok") {
            resultado.lt_antecedentes.forEach(elemento => {
                $("#id_antecedente").append(`<option value="${elemento.id}">${elemento.descripcion}</option>`)
            })
        }
    }
    const limpiar_formulario = () => {
        $("#id_grupo_antecedente").val(0)
        $("#id_antecedente").empty()
        $("#id_descripcion_antecedente").val("")

    }
    const pintar_historia = (lt_historia_detalle) => {

        $("#id_contenedor").empty()

        lt_grupo_antecedente.forEach((el_grupo, index) => {

            lt_historia_detalle.forEach((elemento, index) => {

                if (el_grupo === elemento.id_grupo_antecedente) {

                    $("#id_contenedor").append(
                        `
                        <tr class="text-justify fondo">
                            <td>${elemento.grupo_antecedente} - ${elemento.antecedente} </td>
                            <td>${elemento.descripcion}</td>
                            <td>
                                <a rel="action" data-json='{"accion":"elim" ,"id":"${elemento.id}"}'
                                class="btn btn-danger btn-sm" href="#">Eliminar</a>
                            </td>
                        </tr>
                        `
                    )
                }

            })
        })

        limpiar_formulario()

    }
    const add_historia = async (id_grupo_antecedente, grupo_antecedente, id_antecedente, antecedente, descripcion) => {

        const data = {
            id: id_momentaneo,
            id_grupo_antecedente: id_grupo_antecedente,
            grupo_antecedente: grupo_antecedente,
            id_antecedente: id_antecedente,
            antecedente: antecedente,
            descripcion: descripcion
        }

        id_momentaneo = id_momentaneo + 1
        lt_historia_detalle.push(data)
        pintar_historia(lt_historia_detalle)
    }
    const delete_historia = (id) => {

        lt_historia_detalle = lt_historia_detalle.filter(elemento => elemento.id !== id)
        pintar_historia(lt_historia_detalle)
    }
    $('#id_contenedor').on('click', 'a[rel="action"]', async function () {

        let data = $(this).data('json'),
            action = data.accion,
            id = parseInt(data.id);

        if (action === "elim") {
            delete_historia(id)

        }


    });
    // al cargar pinta el detalle de la historia
    {% for obj_historia_detalle in list_historia_detalle %}
    lt_historia_detalle.push(
        {
            id: id_momentaneo,
            id_grupo_antecedente: parseInt("{{ obj_historia_detalle.antecedente.grupoAntecedente_id }}"),
            grupo_antecedente: "{{ obj_historia_detalle.antecedente.grupoAntecedente }}",
            id_antecedente: parseInt("{{ obj_historia_detalle.antecedente_id }}"),
            antecedente: "{{ obj_historia_detalle.antecedente }}",
            descripcion: "{{ obj_historia_detalle.descripcion }}"
        }
    )
    id_momentaneo = id_momentaneo + 1
    {% endfor %}

    {% for grupo in lt_grupo_antecedentes %}
    lt_grupo_antecedente.push(parseInt("{{grupo.id}}"))
    {% endfor %}

    pintar_historia(lt_historia_detalle)


    $(function () {
        alert("Entro a Historia");
        $("#id_grupo_antecedente").change(async function () {

            const id_grupo_antecedente = parseInt($(this).val())

            if (id_grupo_antecedente !== 0) {

                cargar_combo(id_grupo_antecedente)
            }
        })
        $("#id_registrar_antecedente").click(async function () {

            const id_grupo_antecedente = parseInt($("#id_grupo_antecedente").val()),
                grupo_antecedente = $("#id_grupo_antecedente option:selected").text(),
                id_antecedente = parseInt($("#id_antecedente").val()),
                antecedente = $("#id_antecedente option:selected").text(),
                descripcion = $("#id_descripcion_antecedente").val()

            if (descripcion.length > 0 && id_grupo_antecedente != 0) {
                add_historia(id_grupo_antecedente, grupo_antecedente, id_antecedente, antecedente, descripcion)

            }
            return false

        })
        $("#id_actualizar").click(async function () {

            const parametros = new FormData()
            parametros.append("lt_historia", JSON.stringify(lt_historia_detalle))
            parametros.append("id_paciente", id_paciente)
            parametros.append("action", "update")
            parametros.append("csrfmiddlewaretoken", token)
            parametros.append("notas_internas", descripcion = $("#id_notas_internas").val())

            const response = await fetch(`{% url "atencion:historia" %}`,
                {
                    method: "POST",
                    body: parametros
                }
            )

            const resultado = await response.json()
            if (resultado.result == "ok") {
                alert("Registro actualizado con exito")
            }

        })
    })
</script>
{% endblock %}