clinico/appbase/urls.py
from django.urls import path
from .views import *

app_name = 'base'
urlpatterns = [
    # Paciente
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    # Doctor
    path('Doctor/', DoctorView.as_view(), name='doctor'),
    path('crear_doctor/', CrearDoctorView.as_view(), name='crear_doctor'),
    path('editar_doctor/<int:pk>/', EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
    # Configuracion
    path('Configuracion/', InicioConfiguracion.as_view(), name='configuracion'),

    # Provincia
    path('Configuracion/Lista/Provincia/', ConfiguracionListView.as_view(), name='configuracion_listap'),
    path('Configuracion/Lista/Provincia/Nuevo', CrearProvinciaView.as_view(), name='crear_provincia'),
    path('Configuracion/Lista/Provincia/editar_provincia/<int:pk>/', EditarProvinciaView.as_view(),
         name='editar_provincia'),
    path('Configuracion/Lista/Provincia/eliminar_provincia/<int:pk>/',
         EliminarProvinciaView.as_view(), name='eliminar_provincia'),

    # Ciudad
    path('Configuracion/Lista/Ciudad/', ConfiguracionListCiudadView.as_view(), name='configuracion_listac'),
    path('Configuracion/Lista/Ciudad/Nuevo', CrearCiudadView.as_view(), name='crear_ciudad'),
    path('Configuracion/Lista/Ciudad/editar_ciudad/<int:pk>/', EditarCiudadView.as_view(),
         name='editar_ciudad'),
    path('Configuracion/Lista/Ciudad/eliminar_ciudad/<int:pk>/',
         EliminarCiudadView.as_view(), name='eliminar_ciudad'),

    # Profesion
    path('Configuracion/Lista/Profesion/', ConfiguracionListProfesiondView.as_view(), name='configuracion_listapro'),
    path('Configuracion/Lista/Profesion/Nuevo', CrearProfesionView.as_view(), name='crear_profesion'),
    path('Configuracion/Lista/Profesion/editar_profesion/<int:pk>/', EditarProfesionView.as_view(),
         name='editar_profesion'),
    path('Configuracion/Lista/Profesion/eliminar_profesion/<int:pk>/',
         EliminarProfesionView.as_view(), name='eliminar_profesion'),

    # Titulo
    path('Configuracion/Lista/Titulo/', ConfiguracionListTituloView.as_view(), name='configuracion_listati'),
    path('Configuracion/Lista/Titulo/Nuevo', CrearTituloView.as_view(), name='crear_titulo'),
    path('Configuracion/Lista/Titulo/editar_titulo/<int:pk>/', EditarTituloView.as_view(),
         name='editar_titulo'),
    path('Configuracion/Lista/Titulo/eliminar_titulo/<int:pk>/',
         EliminarTituloView.as_view(), name='eliminar_titulo'),
    # Sangre
    path('Configuracion/Lista/Sangre/', ConfiguracionListSangreView.as_view(), name='configuracion_listasa'),
    path('Configuracion/Lista/Sangre/Nuevo', CrearSangreView.as_view(), name='crear_sangre'),
    path('Configuracion/Lista/Sangre/editar_titulo/<int:pk>/', EditarSangreView.as_view(),
         name='editar_sangre'),
    path('Configuracion/Lista/Sangre/eliminar_titulo/<int:pk>/',
         EliminarSangreView.as_view(), name='eliminar_sangre'),

    # Horario
    path('Configuracion/Lista/Horario/', ConfiguracionListHorarioView.as_view(), name='configuracion_listaho'),
    path('Configuracion/Lista/Horario/Nuevo', CrearHorarioView.as_view(), name='crear_horario'),
    path('Configuracion/Lista/Horario/editar_horario/<int:pk>/', EditarHorarioView.as_view(),
         name='editar_horario'),
    path('Configuracion/Lista/Horario/eliminar_horario/<int:pk>/',
         EliminarHorarioView.as_view(), name='eliminar_horario'),
    # Grupo Antecedente
    path('Configuracion/Lista/Grupo_Antecedente/', ConfiguracionListGAntecedenteView.as_view(),
         name='configuracion_listaga'),
    path('Configuracion/Lista/Grupo_Antecedente/Nuevo', CrearGAntecedenteView.as_view(), name='crear_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/editar_gantecedente/<int:pk>/', EditarGAntecedenteView.as_view(),
         name='editar_gantecedente'),
    path('Configuracion/Lista/Grupo_Antecedente/eliminar_gantecedente/<int:pk>/',
         EliminarGAntecedenteView.as_view(), name='eliminar_gantecedente'),

    #  Antecedente
    path('Configuracion/Lista/Antecedente/', ConfiguracionListAntecedenteView.as_view(),
         name='configuracion_listaa'),
    path('Configuracion/Lista/Antecedente/Nuevo', CrearAntecedenteView.as_view(), name='crear_antecedente'),
    path('Configuracion/Lista/Antecedente/editar_antecedente/<int:pk>/', EditarAntecedenteView.as_view(),
         name='editar_antecedente'),
    path('Configuracion/Lista/Antecedente/eliminar_antecedente/<int:pk>/',
         EliminarAntecedenteView.as_view(), name='eliminar_antecedente'),

    #  Medicamento
    path('Configuracion/Lista/Medicamento/', ConfiguracionListMedicamentoView.as_view(),
         name='configuracion_listame'),
    path('Configuracion/Lista/Medicamento/Nuevo', CrearMedicamentoView.as_view(), name='crear_medicamento'),
    path('Configuracion/Lista/Medicamento/editar_medicamento/<int:pk>/', EditarMedicamentoView.as_view(),
         name='editar_medicamento'),
    path('Configuracion/Lista/Medicamento/eliminar_medicamento/<int:pk>/',
         EliminarMedicamentoView.as_view(), name='eliminar_medicamento'),

    #  Frecuencia
    path('Configuracion/Lista/Frecuencia/', ConfiguracionListFrecuenciaView.as_view(),
         name='configuracion_listafe'),
    path('Configuracion/Lista/Frecuencia/Nuevo', CrearFrecuenciaView.as_view(), name='crear_frecuencia'),
    path('Configuracion/Lista/Frecuencia/editar_frecuencia/<int:pk>/', EditarFrecuenciaView.as_view(),
         name='editar_frecuencia'),
    path('Configuracion/Lista/Frecuencia/eliminar_frecuencia/<int:pk>/',
         EliminarFrecuenciaView.as_view(), name='eliminar_frecuencia'),
    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Dosis
    path('Configuracion/Lista/Dosis/', ConfiguracionListDosisView.as_view(),
         name='configuracion_listado'),
    path('Configuracion/Lista/Dosis/Nuevo', CrearDosisView.as_view(), name='crear_dosis'),
    path('Configuracion/Lista/Dosis/editar_dosis/<int:pk>/', EditarDosisView.as_view(),
         name='editar_dosis'),
    path('Configuracion/Lista/Dosis/eliminar_frecuencia/<int:pk>/',
         EliminarDosisView.as_view(), name='eliminar_dosis'),

    #  Duracion
    path('Configuracion/Lista/Duracion/', ConfiguracionListDuracionView.as_view(),
         name='configuracion_listadu'),
    path('Configuracion/Lista/Duracion/Nuevo', CrearDuracionView.as_view(), name='crear_duracion'),
    path('Configuracion/Lista/Duracion/editar_duracion/<int:pk>/', EditarDuracionView.as_view(),
         name='editar_duracion'),
    path('Configuracion/Lista/Duracion/eliminar_duracion/<int:pk>/',
         EliminarDuracionView.as_view(), name='eliminar_duracion'),
    #  Sintoma
    path('Configuracion/Lista/Sintoma/', ConfiguracionListSintomaView.as_view(),
         name='configuracion_listasin'),
    path('Configuracion/Lista/Sintoma/Nuevo', CrearSintomaView.as_view(), name='crear_sintoma'),
    path('Configuracion/Lista/Sintoma/editar_sintoma/<int:pk>/', EditarSintomaView.as_view(),
         name='editar_sintoma'),
    path('Configuracion/Lista/Sintoma/eliminar_duracion/<int:pk>/',
         EliminarSintomaView.as_view(), name='eliminar_sintoma'),
    #  Diagnostico
    path('Configuracion/Lista/Diagnostico/', ConfiguracionListDiagnosticoView.as_view(),
         name='configuracion_listadia'),
    path('Configuracion/Lista/Diagnostico/Nuevo', CrearDiagnosticoView.as_view(), name='crear_diagnostico'),
    path('Configuracion/Lista/Diagnostico/editar_diagnostico/<int:pk>/', EditarDiagnosticoView.as_view(),
         name='editar_diagnostico'),
    path('Configuracion/Lista/Diagnostico/eliminar_diagnostico/<int:pk>/',
         EliminarDiagnosticoView.as_view(), name='eliminar_diagnostico'),

    #  SignoVital
    path('Configuracion/Lista/SignoVital/', ConfiguracionListSignoVitalView.as_view(),
         name='configuracion_listasv'),
    path('Configuracion/Lista/SignoVital/Nuevo', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('Configuracion/Lista/SignoVital/editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(),
         name='editar_signovital'),
    path('Configuracion/Lista/SignoVital/eliminar_signovital/<int:pk>/',
         EliminarSignoVitalView.as_view(), name='eliminar_signovital'),

    #  Estudio de Gabinete
    path('Configuracion/Lista/EstudioGabinete/', ConfiguracionListEstudioGabineteView.as_view(),
         name='configuracion_listaseg'),
    path('Configuracion/Lista/EstudioGabinete/Nuevo', CrearEstudioGabineteView.as_view(), name='crear_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/editar_estudiogabinete/<int:pk>/', EditarEstudioGabineteView.as_view(),
         name='editar_estudiogabinete'),
    path('Configuracion/Lista/EstudioGabinete/eliminar_estudiogabinete/<int:pk>/',
         EliminarEstudioGabineteView.as_view(), name='eliminar_estudiogabinete'),

    # Agenda
    path('Agenda/', AgendaView.as_view(), name='agenda'),

    # Cita
    path('cita/', CitaView.as_view(), name='cita'),
    path('cita/editar_cita/<int:pk>/', EditarcitaView.as_view(),
         name='editar_cita'),
    path('cita/eliminar_cita/<int:pk>/', EliminarcitaView.as_view(),
         name='eliminar_cita'),




]

clinico/appconsulta/urls.py
from django.urls import path
from .views import *

app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),

# Consulta
    path('consulta/', ConsultaView.as_view(), name='consulta'),

]

clinico/appconsulta/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime, date
from appbase.models import (Paciente, Sintoma, Diagnostico,
                            EstudioGabinete, Medicamento, Dosis, Frecuencia,
                            Duracion, SignoVital, Paciente, Antecedente, GrupoAntecedente)


class Receta(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Atencion', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    motivo = models.CharField('Motivo de Consulta', max_length=50)
    sintoma = models.ForeignKey(Sintoma, on_delete=models.PROTECT)
    exploracion = models.TextField('Exploracion Fisica')
    diagnostico = models.ManyToManyField(Diagnostico, null=True)
    gabinete = models.ManyToManyField(
        EstudioGabinete, null=True)
    instrucciones = models.TextField('Instrucciones Medicas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Receta'
        verbose_name_plural = 'Recetas'

    def __str__(self):
        return '{}'.format(self.fecha)


class DetalleReceta(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    medicamento = models.ForeignKey(Medicamento, on_delete=models.PROTECT)
    cantidad = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    dosis = models.ForeignKey(Dosis, on_delete=models.PROTECT)
    frecuencia = models.ForeignKey(Frecuencia, on_delete=models.PROTECT)
    duracion = models.ForeignKey(Duracion, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'DetalleReceta'
        verbose_name_plural = 'DetalleRecetas'

    def __str__(self):
        return '{}'.format(self.id)


class TomarSignoVital(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.PROTECT)
    signovital = models.ForeignKey(SignoVital, on_delete=models.PROTECT)
    valor = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tomar Signo Vital'
        verbose_name_plural = 'Tomar Signo Vitales'

    def __str__(self):
        return '{}'.format(self.id)


class Historia(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Historia', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    historiaNo = models.CharField('Numero de Historia', max_length=50)
    notasinterna = models.TextField('Notas Internas')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Historia'
        verbose_name_plural = 'Historia Clinicas'

    def __str__(self):
        return '{}'.format(self.fecha)


class HistoriaDetalle(models.Model):
    historia = models.ForeignKey(Historia, on_delete=models.PROTECT)
    GrupoAntecedente = models.ForeignKey(
        GrupoAntecedente, on_delete=models.PROTECT, null=True, blank=True)
    antecedente = models.ForeignKey(Antecedente, on_delete=models.PROTECT)
    descripcion = models.CharField('Antecedente', max_length=300)

    class Meta:
        verbose_name = 'Detalle de la Historia Clinica'
        verbose_name_plural = 'Detalle de las Historias Clinicas'

    def __str__(self):
        return '{}'.format(self.descripcion)

clinico/templates/atencion/agenda/Agenda.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}

    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css"/>


    <style>
        #calendar {
            width: 80%;
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a>Agenda/</a></li>
            </ul>
        </u>
    </div>
    <div class="row" id="conta">

    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/" class="btn btn-danger"><span class="fa fa-caret-left"></span> Regresar</a>
                <a href="/base/cita/" class="btn btn-success"><span class="fa fa-plus"></span> Nuevo Cita</a>
            </div>
        </div>
        <hr>
        <div class="container">
            <div id="calendar"></div>
        </div>
    </div>

    <div class="modal fade" id="myModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form name="frmEliminar" id="frmEliminar" method="GET" action="{% url 'atencion:consulta' %}">
                    {% csrf_token %}
                    <div class="modal-header bg-primary text-light">
                        <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="id" value="">
                        <input type="hidden" name="action" id="action" value="">
                        <input type="hidden" name="fecha" id="fecha" value="">
                        <input type="hidden" name="hora" id="hora" value="">
                        <div class="h3 text-center">
                            <label class="text-primary font-weight-bold">Consultar al Paciente:</label>
                            <span class="text-light font-weight-bold badge badge-danger badge-pill"
                                  id="descripcion"></span><br>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <a rel="action" onclick="eliminaragenda()" class="btn btn-danger btn-sm" href="#">Eliminar</a>
                        <a id="editar" type="button" class="btn btn-info">Editar</a>
                        <button type="submit" class="btn btn-primary">Consulta</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block js %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/locale/es.js"></script>
{% endblock %}
{% block script %}

    <script>
        function eliminaragenda() {
            $('#frmEliminar').attr('action', '{% url 'base:eliminar_cita' 0%} ')
            $('#frmEliminar').attr('method', 'post')
            if (confirm('¿Seguro desea eliminar la cita?')) {
                document.frmEliminar.submit();
            }
        }

        $(document).ready(function () {
            var calendar = $('#calendar').fullCalendar({
                header: {
                    language: 'es',
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                events: [
                    {% for event in agendas %}
                        {
                            title: '{{ event.paciente }}',
                            start: '{{event.fecha|date:"Y-m-d"}} {{ event.hora }}',
                            end: null,
                            id: '{{ event.id }}',

                        },
                    {% endfor %}
                ],

                timeFormat: 'HH:mm',
                selectable: true,
                selectHelper: true,
                editable: false,
                minTime: "07:00:00",
                maxTime: "18:00:00",
                allDaySlot: false,
                slotLabelInterval: '00:15:00',
                slotDuration: "00:15:00",
                defaultTimedEventDuration: '00:15:00',

                select: function (start, end) {
                    var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm");
                },
                eventClick: function (event) {
                    var id = event.id;
                    var nombre = event.title;
                    var fecha = event.start;
                    let date = JSON.stringify(fecha)
                    let hora = JSON.stringify(fecha)
                    date = date.slice(1, 11)
                    hora = hora.slice(12, 17)
                    $('#descripcion').html(nombre);
                    $('#frmEliminar #id').val(id);
                    $('#frmEliminar #fecha').val(date);
                    $('#frmEliminar #hora').val(hora);
                    $('#editar').attr('href', '/base/cita/editar_cita/' + id + '/')
                    $('#myModal').modal('show');

                },

            });
        })
        ;

        function convert(str) {
            var date = new Date(str),
                mnth = ("0" + (date.getMonth() + 1)).slice(-2),
                day = ("0" + date.getDate()).slice(-2);
            return [date.getFullYear(), mnth, day].join("-");
        }
    </script>
{% endblock %}

clinico/templates/atencion/agenda/Cita.html
{% extends "Principal.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/brands.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-5.14.0-web/css/solid.css" %}">
{% endblock %}
{% block body %}
    <img id="fondo2" src="{% static "image/295067 1.png" %}" alt="Fondo Clinico">
    <div id="navegador">
        <u>
            <ul>
                <li><a href="/">Inicio/</a></li>
                <li><a href="/base/Agenda/">Agenda/</a></li>
                <li><a>Nuevo/</a></li>
            </ul>
        </u>
    </div>
    <div class="row" id="conta"></div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="/base/Agenda/" class="btn btn-danger"><span class="fa fa-caret-left"></span>
                    Regresar</a>
            </div>
        </div>
        <hr>

        <u><h2>Nueva Cita</h2></u>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Paciente</label>
                        {{ form.paciente }}
                    </div>

                    <div class="form-group">
                        {% if form.paciente.value != None %}
                            <label for="exampleInputEmail1">Fecha de Consulta</label>
                            {{ form.fecha }}
                        {% else %}
                            <label for="Fnacimiento">Fecha de Consulta</label>
                            <input type="date" name="fecha" class="form-control"
                                   id="id_fecha" value="">
                        {% endif %}

                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Hora</label>
                        {{ form.hora }}
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Motivo de consulta</label>
                        {{ form.motivo }}
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Estado</label>
                        {{ form.estado }}
                    </div>
                    <div>
                        <a href="/base/Agenda/" class="btn btn-danger">Cancelar</a>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>


    </div>

{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% endblock %}